package com.leon.mandelbrot;

import org.apache.hadoop.conf.Configuration;
import org.apache.hadoop.conf.Configured;
import org.apache.hadoop.io.*;
import org.apache.hadoop.mapred.JobConf;
import org.apache.hadoop.mapred.OutputCollector;
import org.apache.hadoop.mapred.Reporter;
import org.apache.hadoop.mapreduce.Mapper;
import org.apache.hadoop.mapreduce.Reducer;
import org.apache.hadoop.util.Tool;
import org.apache.hadoop.util.ToolRunner;

import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.DataInput;
import java.io.DataOutput;
import java.io.IOException;
import java.util.Arrays;
import java.util.Set;

/**
 * A map/reduce program that creates an animation of the mandelbrot set.
 * Given input parameters:
 *  - width: The width of the animated image in pixels
 *  - height: The height of the animated image in pixels
 *  - frames: The amount of the frames
 *  - left X border at beginning
 *  - right X border at beginning
 *  - left X border at end
 *  - right X border at end
 *  - left Y border at beginning
 *  - right Y border at beginning
 *  - left Y border at end
 *  - right Y border at end
 *
 * Mapper:
 *      The mapper's task is to calculate the colors of the given image frame.
 *      The mapper receives a list of key-value pairs to calculate
 *      in which the key is a frame number and the value is a row
 *      number of the specified key.
 *      The map then creates a list of key-value pairs with the key being
 *      the frame number and the value being the row number and an array of
 *      calculated colors.
 * Reducer:
 *      The reducer collects the created list of key-value pairs by key and
 *      then patches together the image for each frame, creating a two-dimensional
 *      array.
 *      The cleanup task then writes the frame into an image file.
 * Final Task:
 *      The final task is to take the iamges generated by the reducer and
 *      create a gif out of them.
 */
public class MandelbrotAnimation extends Configured implements Tool {
    private static final String TMP_DIR_PREFIX = MandelbrotAnimation.class.getSimpleName();

    /**
     * Parses arguments and then runs a map/reduce job.
     * Prints output into standard out.
     *
     * @return 0 if successful, non-zero value if there is an error.
     */
    @Override
    public int run(String[] args) throws Exception {
        return 0;
    }

    /**
     * Main method for running it as a stand alone command.
     */
    public static void main(String[] args) throws Exception {
        System.exit(ToolRunner.run(null, new MandelbrotAnimation(), args));
    }
}
